### ISSUE TITLE
I get disconnected whenever a player dies in my render distance

### ISSUE THREAD

**Issue by Abled-Taha** [cqb13/Numby-hack#10]
I am playing on a server and get disconnected whenever a player dies in my render distance

Here is the [log](https://paste.ee/p/D1btu)

**Comment by cqb13** [comment]
the issue has been fixed in the code, however I have not been able to make a new release yet.

**Comment by Abled-Taha** [comment]
Thanks mate, can you make a new release? As I do not know how to otherwise I would have compiled it myself.
