### ISSUE TITLE
AutoReconnect doesn't work in AutoLog+ 1.19.3

### ISSUE THREAD

**Issue by LaRevoltage** [cqb13/Numby-hack#16]
![image](https://user-images.githubusercontent.com/68560081/210343710-4324615d-d5f5-4447-b693-4ab3cce96422.png)

**Comment by cqb13** [comment]
There is no auto reconnect in auto log +. There is a toggle auto reconnect option witch turns off auto reconnect if you have it on. I just tested it and it does seem to work. 

could you give more info on your issue.
