### ISSUE TITLE
Discord Rich Presence is overwritten by Numby Rich presence

### ISSUE THREAD

**Issue by D-a-r-n-o-l-d** [cqb13/Numby-hack#21]
title is self-explanatory,  the numby rich presence takes priority over the built in module, preventing custom rich presence.

**Comment by cqb13** [comment]
wdym "preventing custom rich presence", it overides the default meteor icon, and changes the default text, but thats about it, and the text is something you should be able to change. If you want to normal meteor icon thing, I can add a toggle for it.
