### ISSUE TITLE
Discord presence can't be disabled

### ISSUE THREAD

**Issue by Max-Gouliaev** [cqb13/Numby-hack#22]

**Comment by cqb13** [comment]
wdym, cant be disabled? I tested it, and it turns off just fine.  Please give more info. If you mean that you cant use the normal meteor discord presence, I am aware of that issue and it will be fixed in the next release.

**Comment by Max-Gouliaev** [comment]
How do you disable it?

**Comment by cqb13** [comment]
you turn off the module, like any other module.
![image](https://github.com/cqb13/Numby-hack/assets/74616162/b34a74ba-bf67-47e5-9128-083224bb13da)

**Comment by Max-Gouliaev** [comment]
OH! Sorry, didn't realize that Numby settings are in meteor's module
