### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by Ebanytiy** [cqb13/Numby-hack#23]
meteor client updated to 1.20

**Comment by cqb13** [comment]
ya ik, I have final exams this week and have had no time to work on the client. I should be able to update it by Saturday or Sunday.

**Comment by breadtard** [comment]
hey its sunday how are things looking

**Comment by cqb13** [comment]
lol forgot about it, ill do it rn

**Comment by breadtard** [comment]
thank you kind sir
