### ISSUE TITLE
Can you update the version to 1.20.1 as soon as possible please!

### ISSUE THREAD

**Issue by Python9874** [cqb13/Numby-hack#26]
Everyone wants meteor client addons to support 1.20.1. Would you mind updating it to 1.20.1 the jar file so if i'm on Meteor version 1.20.1 it is compatible with fabric. Thanks alot: Seb!

**Comment by cqb13** [comment]
1.20 addon should work with 1.20.1 meteor, but I can update

**Comment by cqb13** [comment]
updated
