### ISSUE TITLE
New Chunks crashes Sodium renderer

### ISSUE THREAD

**Issue by ToneXum** [cqb13/Numby-hack#57]
Whenever the new chunks module is enabled, the renderer crashes with:
```
Connection Lost:

Internal Exception: java.lang.IllegalStateException: Accessing OpenGL funtions outside from the main render thread is not supported when using Sodium.
```
Sodium is, as indicated, installed.

Disabling the module will cause it to not crash the renderer.

Minecraft: 1.20.4
Numby version: Build 28

**Comment by ToneXum** [comment]
Going through the logs did not reveal anything interesting. Its simply closes the server (for singleplayer worlds) and disconnects the client.

**Comment by cqb13** [comment]
Thank you for letting me know, I will look into this and fix this right now. However just to let you know, 1.20.4 is no longer supported, as I stay updated with the latest dev build, so the fixed version will be for 1.20.6.

**Comment by ToneXum** [comment]
![https://tenor.com/view/sad-crying-emoji-shouting-gif-26048814]

**Comment by cqb13** [comment]
Should be fixed now. Sorry for the wait; some things came up
